spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 5
      max-active: 100
      max-idle: 10
      min-idle: 5
      test-on-borrow: true
      test-on-return: true
      test-on-connect: true
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        max_fetch_depth: 3
        jdbc:
          fetch_size: 500
          batch_size: 30
        temp:
          use_jdbc_metadata_defaults: false

  data:
    jpa:
      repositories:
        enabled: true
debug: false